import enumValuesJson from "@duet3d/objectmodel/dist/enums.json";
import { normalisePath } from "./paths";

/**
 * Map of full object-model paths (with `[]` standing for any array index) to the list of valid enum / string-
 * literal values the field can take. Generated by @duet3d/objectmodel's build script from its TS sources.
 */
const enumValues: Record<string, string[]> = enumValuesJson as Record<string, string[]>;

/**
 * Return the list of valid values for a given object-model path, or null if the path has no known enum values.
 */
export function getEnumValuesForPath(path: string): string[] | null
{
	if (!path)
	{
		return null;
	}
	const key = normalisePath(path);
	return Object.prototype.hasOwnProperty.call(enumValues, key) ? enumValues[key] : null;
}